server:
  port: 8080
  servlet:
    context-path: /demo03-springSecurity-springboot
    session:
      timeout: 3600s

spring:
  application:
    name: security-springboot
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
